//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.StudioCore.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP.StudioCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;401 Unauthorized&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;center&gt;&lt;h1&gt;401 Unauthorized&lt;/h1&gt;&lt;/center&gt;
        ///    &lt;hr /&gt;
        ///    &lt;center&gt;SP.StudioCore/1.0.0.0&lt;/center&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string _401 {
            get {
                return ResourceManager.GetString("_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--顶级域名列表--&gt;
        ///&lt;root&gt;
        ///  &lt;item&gt;.app&lt;/item&gt;
        ///  &lt;item&gt;.art&lt;/item&gt;
        ///  &lt;item&gt;.bid&lt;/item&gt;
        ///  &lt;item&gt;.bio&lt;/item&gt;
        ///  &lt;item&gt;.biz&lt;/item&gt;
        ///  &lt;item&gt;.cab&lt;/item&gt;
        ///  &lt;item&gt;.cam&lt;/item&gt;
        ///  &lt;item&gt;.ceo&lt;/item&gt;
        ///  &lt;item&gt;.com&lt;/item&gt;
        ///  &lt;item&gt;.dev&lt;/item&gt;
        ///  &lt;item&gt;.dog&lt;/item&gt;
        ///  &lt;item&gt;.fyi&lt;/item&gt;
        ///  &lt;item&gt;.how&lt;/item&gt;
        ///  &lt;item&gt;.ink&lt;/item&gt;
        ///  &lt;item&gt;.ist&lt;/item&gt;
        ///  &lt;item&gt;.law&lt;/item&gt;
        ///  &lt;item&gt;.lol&lt;/item&gt;
        ///  &lt;item&gt;.ltd&lt;/item&gt;
        ///  &lt;item&gt;.mba&lt;/item&gt;
        ///  &lt;item&gt;.men&lt;/item&gt;
        ///  &lt;item&gt;.moe&lt;/item&gt;
        ///  &lt;item&gt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
    }
}
