var GolbalSetting={Site:{},Enum:{}};window.BW||(window.BW={});
(function(e){e.BindEvent=new Class({Implements:[Events,Options],options:{action:null,type:null,event:null,data:null,search:null,pagesplit:null,pageindex:1,pagesize:20,load:null,callback:null,target:null,stop:!1,"confirm-tip":"\u786e\u8ba4\u8981\u8fdb\u884c\u8be5\u64cd\u4f5c\u5417\uff1f",postdata:"betwin-postdata"},setData:function(a){this.dom.element.store(this.options.postdata,a)},loading:null,dom:{element:null,container:null,searchbox:null,pagesplit:null,elements:{}},loadOptions:function(a){var b=
this;Object.forEach(Element.GetAttribute(b.dom.element,"data-bind-"),function(a,d){b.options[d]||(b.options[d]=a)})},initialize:function(a,b){var c=this;c.setOptions(b);c.dom.element=a=$(a);c.loadOptions();switch(c.dom.element.get("tag")){case "form":c.options.type="form",c.dom.element.set("action",c.options.action)}if(a=c.getPostData())c.options.data=a;c.dom.container=c.options.target?$(c.options.target):c.dom.element;c.load();c.loadOptions();c.options.search&&(c.dom.searchbox=$(c.options.search));
if(c.options.search&&null==c.dom.searchbox)alert("\u6307\u5b9a\u7684\u641c\u7d22\u6846\u5bf9\u8c61"+c.options.search+"\u4e0d\u5b58\u5728");else if(c.options.pagesplit&&(c.dom.pagesplit=$(c.options.pagesplit)),c.options.pagesplit&&null==c.dom.pagesplit)alert("\u6307\u5b9a\u7684\u5206\u9875\u63a7\u4ef6"+c.options.pagesplit+"\u4e0d\u5b58\u5728");else if(null!=c.dom.container)switch(c.loading=c.options.loading||"loading-"+c.options.type,c.options.stop||c.fire(),c.options.event){case "click":case "submit":case "touchend":c.dom.element.addEvent(c.options.event,
function(){c.fire.apply(c)});break;case "confirm":c.dom.element.addEvent("click",function(){new BW.Tip(c.options["confirm-tip"],{type:"confirm",callback:function(){c.fire.apply(c)}})})}},load:function(){var a=this;a.options.load&&a.options.load.split(",").each(function(b){e.load[b]&&e.load[b].apply(a)})},run:function(a,b){var c=this;b||(b=c.options.callback);b&&("object"==typeof a&&!a.success&&BW.callback["golbal-error"]&&BW.callback["golbal-error"].apply(c,[a]),b.split(",").each(function(b){e.callback[b]&&
e.callback[b].apply(c,[a])}))},updateDelay:function(){this.dom.container.getElements("[data-bind-action-delay]").each(function(a){var b=a.get("data-bind-action-delay");a.set("data-bind-action",b);a.set("data-bind-action-delay",null)})},bindAction:function(){this.updateDelay();this.dom.container.getElements("[data-bind-action]").each(function(a){e.Bind(a)})},getPostData:function(){var a=this,b={};a.dom.element.get("data-bind-data")&&a.dom.element.get("data-bind-data").split(",").each(function(c){switch(c){case "parent":c=
a.dom.element.getParent("[data-bind-post]");null!=c&&(b=Object.merge(b,c.get("data-bind-post").parseQueryString()));break;case "url":(c=location.search)&&0==c.indexOf("?")&&(c=c.substr(1),b=Object.merge(b,c.parseQueryString()));break;case "form":(c=a.dom.element.getParent("form"))&&(b=Element.GetData(c));break;default:c.contains("=")&&(b=Object.merge(b,c.parseQueryString()))}});if(a.dom.searchbox){var c=Element.toQueryString(a.dom.searchbox).parseQueryString();b=Object.merge(c,b)}a.dom.element.retrieve(a.options.postdata)&&
(b=Object.merge(b,a.dom.element.retrieve(a.options.postdata)));a.options.pageindex&&"1"!=a.options.pageindex&&"list"==a.options.type&&(b.PageIndex=a.options.pageindex);return b},fire:function(a){this[this.options.type]&&this[this.options.type].apply(this,[a])},control:function(){var a=this;(new Request.HTML({url:a.options.action,onRequest:function(){a.dom.container.addClass(a.loading)},onComplete:function(){a.dom.container.removeClass(a.loading)},onSuccess:function(b,c,d,g){a.dom.container.set("html",
d);a.run(d);a.bindAction()}})).get()},ajax:function(a){var b=this,c=b.getPostData();(new Request.JSON({url:b.options.action,onRequest:function(){b.dom.container.addClass(b.loading)},onComplete:function(){b.dom.container.removeClass(b.loading)},onFailure:function(a){switch(a.status){case 503:a=null;break;default:a=a.response}a&&(a=a.replace(/<a .+?<\/a>/g,"BetWin 2.0.1"),new BW.Tip(a))},onSuccess:function(c){b.run(c,a);b.bindAction()}})).post(c)},form:function(){var a=this,b=a.dom.element,c=b.get("id");
c||(c="form-"+(new Date).getTime(),b.set("id",c));var d=!1;b.getElement("[type=file]")&&(d=!0);var g={onRequest:function(){b.addClass(a.loading)},onComplete:function(){b.removeClass(a.loading)},onFailure:function(a){new BW.Tip(a.response)},onSuccess:function(b){b=JSON.decode(b);a.run(b)}};b.set({"data-bind":!0,send:g,events:{submit:function(c){c&&c.stop();var k=!0;b.getElements("[data-regex]").each(function(a){k&&!Regex.test(a.get("data-regex"),a.get("value"))&&(new BW.Tip(a.get("placeholder"),{callback:function(){a.focus()}}),
k=!1)});if(k)if(d){var f=new XMLHttpRequest;f.open("POST",b.get("action"),!0);f.onload=function(a){g.onComplete();if(200==f.status)g.onSuccess(f.response);else g.onFailure(f)};g.onRequest();f.send(new FormData(b))}else"search"==b.get("data-bind-type")?e.Bind(a.dom.container).fire():this.hasClass(a.loading)||(Object.forEach(a.getPostData(),function(a,c){var d=b.getElement("input[name="+c+"]");null==d&&(d=new Element("input",{type:"hidden",name:c}),d.inject(b));d.set("value",a)}),b.send())}}})},list:function(){var a=
this,b=a.getPostData();(new Request.JSON({url:a.options.action,onRequest:function(){a.dom.container.addClass(a.loading)},onComplete:function(){a.dom.container.removeClass(a.loading)},onSuccess:function(b){a.run(b);a.bindAction()}})).post(b)}});e.Bind=function(a){null==a.retrieve("bind")&&a.store("bind",new BW.BindEvent(a));return a.retrieve("bind")}})(BW);
(function(e){e.Update=new Class({Implements:[Events,Options],options:{action:null,name:null},dom:{element:null,tag:null,type:null},restore:function(a){var b=this,c=b.dom.element;new BW.Tip(a,{callback:function(){switch(b.dom.type){case "checkbox":c.set("checked",c.retrieve("value"));break;default:c.set("value",c.retrieve("value"))}}})},initialize:function(a,b){var c=this;c.dom.element=a=$(a);c.setOptions(b);Object.forEach(Element.GetAttribute(a,"data-update-"),function(a,b){c.options[b]=a});b=a.get("tag");
var d=null;switch(b){case "input":switch(a.get("type")){case "checkbox":case "radio":d="checkbox";"true"==a.get("data-checked")&&a.set("checked",!0);break;default:d="text"}break;case "select":case "textarea":d="text"}c.dom.tag=b;c.dom.type=d;a.addEvents({focus:function(a){switch(d){case "checkbox":this.store("value",this.get("checked"));break;default:this.store("value",this.get("value"))}},change:function(b){b=Object.clone(c.options);switch(d){case "checkbox":b.value=a.get("checked")?1:0;break;case "text":b.value=
a.get("value")}(new Request.JSON({url:c.options.action,onRequest:function(){a.set("disabled",!0)},onComplete:function(){a.set("disabled",!1)},onFailure:function(a){c.restore(a.statusText)},onSuccess:function(b){b.success?(a.highlight(),new BW.Tip(b.msg,{delay:3E3,type:"tip",mask:!1,drag:!1})):c.restore(b.msg)}})).post(b)}})}})})(BW);
(function(e){e.callback={html:function(a){var b=this.dom.container.retrieve("html",this.dom.container.get("html"));this.dom.container.store("html",b);a.info&&(this.dom.container=this.dom.container.set("html",b.toHtml(a.info)))},"html-img":function(a){this.dom.container.getElements("img[data-src]").each(function(a){a.set("src",a.get("data-src"));a.set("data-src",null)})},"html-field":function(a){a.success?this.dom.container.getElements("[data-bind-html]").each(function(b){var c=b.retrieve("html",b.get("html"));
b.store("html",b);b.set("html",c.toHtml(a.info))}):new BW.Tip(a.msg)},"html-tpl":function(a){if(a.success){var b=this.dom.container.getElement("[data-list-element]");if(null==b)alert("\u5217\u8868\u5bf9\u8c61\u4e2d\u6ca1\u6709\u6307\u5b9adata-list-element\u5bf9\u8c61");else{var c=$(this.dom.element.get("data-bind-tpl-template"));null==c&&(c=b);var d=c.retrieve("template");null==d&&(d=c.get("value"),c.store("template",d));console.log(d);laytpl(d).render(a.info,function(a){b.set("html",a)})}}else new BW.Tip(a.msg)},
list:function(a){if(a.success){var b=this.dom.container.getElement("[data-list-element]");if(null==b)alert("\u5217\u8868\u5bf9\u8c61\u4e2d\u6ca1\u6709\u6307\u5b9adata-list-element\u5bf9\u8c61");else{var c=b.retrieve("template");null==c&&(c=b.get("html"),b.store("template",c));b.empty();a.info||(a.info={list:[],RecordCount:0,PageIndex:0,PageSize:20});var d=[];a.info.length&&(a.info={RecordCount:a.info.length,list:a.info});if(0==a.info.RecordCount){var g=b.get("data-none-tip")||"\u6ca1\u6709\u7b26\u5408\u5f53\u524d\u6761\u4ef6\u7684\u8bb0\u5f55";
b.addClass("bw-list-none");switch(b.get("tag")){case "table":case "tbody":var f=this.dom.container.getElement("thead");f&&(f=f.getElements("tr th").length,d.push('<tr><td colspan="'+f+'"><p class="am-alert am-text-center">'+g+"</p></td></tr>"));break;case "ul":d.push('<li class="bw-list-none"><p>'+g+"</p></li>");break;default:d.push("")}}else a.info.list.each(function(a){d.push(c.toHtml(a))});b.set("html",d.join(""));null!=this.dom.pagesplit&&e.callback.pagesplit.apply(this,[a])}}else new BW.Tip(a.msg)},
pagesplit:function(a){var b=this,c=b.dom.pagesplit;c.empty();var d=a.info;d.PageIndex=d.PageIndex.toInt();var g=d.MaxPage=0==d.RecordCount%d.PageSize?d.RecordCount/d.PageSize:Math.floor(d.RecordCount/d.PageSize)+1;if(0!=g){var e=function(a){b.options.pageindex=a;b.fire()};switch(b.dom.element.get("data-platform")){case "mobile":!function(){var a=new Element("ul",{"class":"pagesplit-mobile"});(new Element("li",{text:"\u4e0a\u4e00\u9875","class":"nav "+(1==d.PageIndex?"disabled":""),events:{click:function(){e.apply(b,
[Math.max(1,d.PageIndex-1)])}}})).inject(a);for(var f=new Element("li",{"class":"jump"}),l=new Element("select",{events:{change:function(){var a=this.get("value");e.apply(b,[a])}}}),h=1;h<=g;h++)(new Element("option",{value:h,text:"\u7b2c"+h+"\u9875",selected:h==d.PageIndex})).inject(l);l.inject(f);f.inject(a);(new Element("li",{text:"\u4e0b\u4e00\u9875","class":"nav "+(d.PageIndex==g?"disabled":""),events:{click:function(){var a=Math.min(g,d.PageIndex+1);console.log(d);e.apply(b,[a])}}})).inject(a);
a.inject(c)}();break;default:!function(){var a=new Element("ul",{"class":"pageSplit"});(new Element("li",{"class":"",html:"${RecordCount}\u6761\u8bb0\u5f55 ${PageIndex}/${MaxPage}\u9875".toHtml(d)})).inject(a);(new Element("li",{"class":1==d.PageIndex?"am-disabled":"",title:"\u9996\u9875",html:'<a href="javascript:" data-page="1" class="am-icon-backward am-text-xs"></a>'})).inject(a);for(var f=Math.max(1,d.PageIndex-3);f<=Math.min(d.PageIndex+3,g);f++)(new Element("li",{"class":f==d.PageIndex?"am-active":
"",html:'<a href="javascript:" data-page="'+f+'">'+f+"</a>"})).inject(a);(new Element("li",{"class":"",html:'<input title="\u8df3\u8f6c" type="number" min="1" max="'+g+'" value="'+d.PageIndex+'" style="width:'+Math.max(60,d.PageIndex.toString().length+12)+'px;" />'})).inject(a);(new Element("li",{"class":d.PageIndex==g?"am-disabled":"",title:"\u672b\u9875",html:'<a href="javascript:" data-page="'+d.MaxPage+'" class="am-icon-forward am-text-xs"></a>'})).inject(a);a.inject(c);a.getElements("a").addEvent("click",
function(a){this.hasClass("am-disabled")||this.hasClass("am-active")||e.apply(b,[this.get("data-page")])});a.getElement("input[type=number]").addEvent("change",function(){var a=this.get("value").toInt();isNaN(a)||1>a||a>d.MaxPage?this.set("value",d.PageIndex):e.apply(b,[a])})}()}}},fire:function(a){a=this;a=null==a.dom.element.get("data-bind-fire-target")?a.dom.element:$(a.dom.element.get("data-bind-fire-target"));null==a?alert("\u6307\u5b9a\u7684\u6267\u884c\u5bf9\u8c61\u4e3a\u7a7a data-bind-fire-target"):
(a=e.Bind(a),a.fire())},"success-fire":function(a){a.success&&e.callback.fire.apply(this)},"error-tip":function(a){if(!a.success){var b=this;new BW.Tip(a.msg,{callback:function(){var c=b.dom.element.get("data-bind-error-tip");c&&BW.callback[c]&&b.run(a,c)}})}},tip:function(){e.load.tip.apply(this)},"form-fill":function(a){var b=this;if(a.success){var c=a.info;null==c?new BW.Tip("\u7ed1\u5b9a\u63a7\u4ef6\u4e3a\u7a7a"):b.dom.container.getElements("[name],[data-name]").each(function(b){var d=b.get("data-name")||
b.get("name");if(d=Object.getValue(c,d)){var e=b.get("data-fill-format");e&&htmlFunction[e]&&(d=htmlFunction[e](d));switch(b.get("type")){case "checkbox":b.set("checked",1==d||"true"==d);break;case "image":b.set("src",d);break;case "datetime-local":d=htmlFunction["datetime-local"](d);b.set("value",d);break;case "file":break;default:switch(b.get("tag")){case "select":b.set("data-selected",d);break;case "img":b.set("src",d);break;case "span":case "div":case "label":case "p":b.set("html",d)}b.set("value",
d)}Object.each(Element.GetAttribute(b),function(c,d){/\$\{(.+?)\}/.test(c)&&(c=c.toHtml(a.info),b.set("data-"+d,c))})}})}else new BW.Tip(a.msg,{callback:function(){var c=b.dom.element.get("data-bind-form-fill-faild");c&&b.run(a,c)}})},"form-tip":function(a){var b=this;new BW.Tip(a.msg,{callback:function(){if(a.success){"form"==b.dom.element.get("tag")&&b.dom.element.reset();var c=b.dom.element.get("data-bind-form-tip");c&&b.run(a,c)}}})},"form-refser":function(a){if(a.success){a=this.dom.element.get("data-bind-refser");
if(null==a)return null;a=$(a);if(null==a)return null;e.Bind(a).fire()}},"delete":function(a){var b=this;new BW.Tip(a.msg,{callback:function(){if(a.success){var c=b.dom.element.getParent("[data-bind-delete]");null!=c&&c.dispose()}}})},"diag-close":function(a){a=this.dom.element.getParent(".diag[data-name]");if(null!=a){a=a.get("data-name");if(!BW.diagObj[a]||!BW.diagObj[a].target)return null;BW.diagObj[a].target.Close()}},select:function(a){var b=this;if(a.info){var c=b.dom.element.get("data-selected");
"array"==typeOf(a.info)&&(a.info={list:a.info,recordCount:a.info.length});if(!a.info.list)Object.forEach(a.info,function(a,d){var e=new Element("optgroup",{label:d});Object.forEach(a,function(a,b){(new Element("option",{text:a,value:b,selected:c==b?!0:null,"data-option":1})).inject(e)});e.inject(b.dom.element)});else if("select"==b.dom.element.get("tag")){var d=b.dom.element.get("data-select-value")||"value",e=b.dom.element.get("data-select-text")||"text";b.dom.element.getElements("[data-option]").dispose();
a.info.list.each(function(a){(new Element("option",{text:a[e],value:a[d],selected:c==a[d]?!0:null,"data-option":1})).inject(b.dom.element)})}}},count:function(a){if(a.success){var b=this.dom.container.getElement("[data-list-element]");if(null!=b&&(b=b.getNext("tfoot,.list-tfoot"),null!=b)){var c=b.retrieve("html",b.get("html"));b.store("html",c);b.set("html",c.toHtml(a.info))}}},tab:function(a){var b={};this.dom.container.getElements("[data-tab-link],[data-tab-target]").each(function(a){var c=a.get("data-tab-link"),
e=a.get("data-tab-target");c&&(b[c]||(b[c]={link:[],target:[]}),a.get("data-tab-current")&&(b[c].current=a.get("data-tab-current")),b[c].link.push(a));e&&(b[e]||(b[e]={link:[],target:[]}),b[e].target.push(a))});Object.forEach(b,function(a,b){if(a.link.length==a.target.length){var c=a.current||"current";a.link.each(function(b,d){b.addEvent("click",function(){b.hasClass(c)||(a.link.removeClass(c),a.target.setStyle("display","none"),this.addClass(c),a.target[d].setStyle("display","block"))})});a.link[0].fireEvent("click")}})},
"image-upload":function(a){this.dom.element.getElements("img[data-upload]").each(function(a){(new Element("input",{type:"file"})).inject(a)})},update:function(){var a=this;a.dom.element.getElements("[data-update-name]").each(function(b){var c=b.get("data-bind-update-action")||a.dom.element.get("data-bind-update-action");if(null==c){var d=b.getParent("[data-bind-update-action]");null!=d&&(c=d.get("data-bind-update-action"))}new BW.Update(b,{action:c})})},checked:function(){this.dom.element.getElements("[type=checkbox]").each(function(a){"1"==
a.get("data-checked")&&a.set("checked",!0)})}};e.load={tip:function(){this.dom.element.getElements("[placeholder]").addEvents({focus:function(){var a=this.get("placeholder");if(null!=a&&""!=a){var b=this.getNext();if(null==b||!b.hasClass("input-tip")){b=this.getParent(".diag");var c=this.getParent(".page-header");b=null==b?this.getPosition(c):this.getPosition(b);b=new Element("span",{"class":"input-tip",styles:{left:b.x,top:b.y},text:a});b.inject(this,"after")}b.addClass.delay(100,b,["focus"])}},
blur:function(){var a=this.getNext();null!=a&&a.hasClass("input-tip")&&a.removeClass("focus")}});this.dom.element.getElements("[data-type=datetime],[data-type=date]").each(function(a){var b=a.get("id");null==b&&(b="datetime_"+Math.round(1E5*Math.random()),a.set("id",b));a.get("data-type")})},search:function(){for(var a=null,b=this.dom.container;"body"!=b.get("tag")&&!(a=b.getElement("form"));)b=b.getParent();null!=a&&(b=a.get("id"),null==b&&(b="search-"+(new Date).getTime(),a.set("id",b)),this.dom.element.set("data-bind-search",
b),a.set("onsubmit","return false;"),b=this.dom.element.get("id"),null==b&&(b="list-"+(new Date).getTime(),this.dom.element.set("id",b)),a=a.getElement("input[type=submit]"),null!=a&&a.set("data-event-fire",b))},pagesplit:function(){var a=this.dom.container.getNext(".pageSplit");null==a&&(a=new Element("div",{"class":"pageSplit",id:"pagesplit-"+(new Date).getTime()}),a.inject(this.dom.container,"after"));a=a.get("id");null==a&&(a="pagesplit-"+(new Date).getTime());this.dom.element.set("data-bind-pagesplit",
a)},"form-parent":function(){var a=this,b=a.dom.element.getParent("[data-bind-post]");null!=b&&(b=b.get("data-bind-post").parseQueryString(),Object.forEach(b,function(b,d){var c=a.dom.element.getElement("[name="+d+"]");null==c&&(c=new Element("input",{name:d,type:"hidden"}),c.inject(a.dom.element));c.set("value",b)}))},"list-sort":function(){var a=this;if("table"==a.dom.element.get("tag")){var b=function(b){var c=a.dom.element.retrieve("sort");if(c){var e=c.get("data-list-sort-index").toInt(),f=a.dom.element.getElement("[data-list-element]");
c=f.getElements("tr").map(function(a){if(null!=a.getElement("[colspan]"))return null;var b=a.getElements("td")[e].get("text");b=b.replace(/[\uffe5,%]/g,"").toFloat();return{value:b,item:a}});c.sort(function(a,c){if(!a||!c||isNaN(a.value)||isNaN(c.value))return 0;switch(b){case "asc":return a.value>c.value?1:-1;case "desc":return a.value>c.value?-1:1}return 0});c.each(function(a){a&&a.item.inject(f,"bottom")})}};a.dom.element.getElements("thead th").each(function(c,d){c.get("data-list-sort")&&(d=new Element("label",
{html:c.get("html"),"data-list-sort-index":d,"data-list-sort-action":null,"class":"sort",events:{click:function(){var c=a.dom.element.retrieve("sort");c&&(c.removeClass("asc"),c.removeClass("desc"));c=this.get("data-list-sort-action");switch(c){case "asc":case null:c="desc";break;case "desc":c="asc"}this.set("data-list-sort-action",c);this.addClass(c);a.dom.element.store("sort",this);b(c)}}}),c.empty(),d.inject(c))})}},dom:function(){var a=this;a.dom.container.getElements("[data-dom]").each(function(b){a.dom.elements[b.get("data-dom")]=
b})}};e._post={status:!1,list:[],run:function(){this.status||(0==this.list.length?this.status=!1:this.list[0].post())}};e.POST=function(a,b,c){c||(c={});a=new Request.JSON({url:a,data:b,onRequest:function(){e._post.status=!0},onComplete:function(){e._post.list.shift();e._post.status=!1;e._post.run.delay(100,e._post)},onSuccess:function(a){c.callback&&c.callback.apply(this,[a])}});e._post.list.push(a);e._post.run()}})(BW);
(function(e){e.callback["mobile-check"]=function(){var a=this,b=null;if(b=a.dom?a.dom.element.getElement("div"):a.getElement("div")){var c=b.get("data-hide");!function(){c&&(c=c.split(","));["header","footer"].each(function(a){Frame[a]&&(c&&c.contains(a)?Frame[a].addClass("hide"):Frame[a].removeClass("hide"))})}();!function(){if("footer"!=c&&Frame.footer){var a=b.get("data-home");Frame.footer.getElements("[data-home]").each(function(b){b.get("data-home")==a?b.addClass("current"):b.removeClass("current")})}}();
!function(){if(Frame.title){var a=b.get("data-title");a||(a=Frame.list.getLast());Frame.title.set("html",a)}}();!function(){if(Frame.setting){var a=b.get("data-setting-name");a?(Frame.setting.addClass("show"),Frame.setting.set({html:a,href:"javascript:"+b.get("data-setting-href")})):Frame.setting.removeClass("show")}}();!function(){var c=b.get("data-callback");c&&c.split(",").each(function(b){e.callback[b]&&e.callback[b].apply(a)})}();!function(){Platform.app||b.getElements("[data-app=x5]").each(function(a){a.dispose()})}()}};
e.callback["mobile-tab"]=function(){var a=this.dom.element.getElements("[data-tab-index]");if(0!=a.length){var b={};this.dom.element.getElements("[data-tab-content]").each(function(a){b[a.get("data-tab-content")]=a});var c=a.filter(function(a){return a.hasClass("current")}).getLast(),d=null;c&&(d=b[c.get("data-tab-index")]);a.addEvent("touchend",function(a){c!=this&&(c&&c.removeClass("current"),a=this.get("data-tab-index"),this.addClass("current"),c=this,d&&d.removeClass("show"),b[a]&&(b[a].addClass("show"),
d=b[a]))})}};e.callback["mobile-back"]=function(){Frame.back()};e.callback["mobile-dispose"]=function(){var a=this,b=null,c=null;a.dom?(c=a.dom.element,b=a.dom.element.getElement("div")):(c=b,b=a.getElement("div"));b&&b.get("data-dispose")&&b.get("data-dispose").split(",").each(function(b){e.callback[b]&&e.callback[b].apply(a)});c.dispose()}})(BW);
(function(e){e.FrameObj=null;e.Frame=new Class({Implements:[Events,Options],options:{action:null,name:null},data:{container:null,cache:{}},initialize:function(a,b){var c=e.FrameObj=this;c.setOptions(b);c.data.container=$(a)},open:function(a,b){b||(b={});b.id||(b.id=a);b.in||(b.in="right");Object.forEach(this.data.cache,function(a,b){a.getElements(".bw-off-canvas-wrap.active").each(function(a){a.removeClass("active")})});this.data.cache[b.id]||(this.data.cache[b.id]=new Element("div",{"class":"bw-frame-item in-"+
b.in,id:b.id,"data-bind-action":a,"data-bind-type":"control","data-bind-load":"frame-item","data-bind-callback":"frame-item"}));b.data&&this.data.cache[b.id].set("data-bind-post",Object.toQueryString(b.data));b.active&&this.data.cache[b.id].addClass("active");this.data.cache[b.id].inject(this.data.container);new BW.Bind(this.data.cache[b.id])},back:function(a,b){var c=this;b||(b={});var d=a.getPrevious(".bw-frame-item");d?(d.addClass("active"),b.reload&&d.getBindEvent().fire(),function(){a.dispose();
c.data.cache[a.get("id")]&&delete c.data.cache[a.get("id")]}.delay(300)):history.back()}});BW.load["frame-item"]=function(){var a=this;a.dom.element.addEvent("tap",function(b){b=$(b.target);if(b.get("data-off-canvas")){var c=$(b.get("data-off-canvas"));c&&c.toggleClass("active")}if(b.get("data-frame"))switch(b.get("data-frame")){case "back":BW.FrameObj.back(a.dom.element)}b.hasClass("bw-off-canvas-wrap")&&b.removeClass("active")})};BW.callback["frame-item"]=function(){var a=this,b=a.dom.element.getPrevious(".bw-frame-item");
b&&(b.removeClass("active"),b.scrollTo.delay(500,b,[0,0]));a.dom.element.addClass("active");["right","left","top","bottom"].each(function(b){a.dom.element.removeClass("in-"+b)})}})(BW);
(function(e){e.Tip=new Class({Implements:[Events,Options],options:{callback:null,mask:!0,drag:!0,cssname:null,title:"\u7cfb\u7edf\u63d0\u793a",type:"alert",delay:0,width:null},dom:{alert:null,mask:null},message:null,initialize:function(a,b){var c=this;c.setOptions(b);b=[];c.options.title&&b.push('<div class="title">'+c.options.title+"</div>");b.push('<div class="content"><div class="content-msg">'+a+'</div><p class="button"></p></div>');c.dom.alert=new Element("div",{id:"bw-tip","class":"bw-tip bw-tip-hide bw-tip-"+
c.options.type,html:b.join("")});c.options.cssname&&c.dom.alert.addClass(c.options.cssname);c.options.width&&c.dom.alert.setStyle("width",c.options.width);a=c.dom.alert.getElement(".button");switch(c.options.type){case "alert":c.dispose();c.dom.alert.inject(document.body);(new Element("a",{href:"javascript:",text:"\u786e\u5b9a","class":"alert-btn-submit",events:{click:function(){c.options.callback&&c.options.callback.apply(c);c.close()}}})).inject(a);!function(){var a=c.dom.alert.getSize();c.dom.alert.setStyles({"margin-left":a.x/
-2,"margin-top":a.y/-2})}();break;case "confirm":c.dispose();c.dom.alert.inject(document.body);(new Element("a",{href:"javascript:",text:"\u786e\u5b9a","class":"alert-btn-submit",events:{click:function(){c.options.callback&&c.options.callback.apply(c);c.close()}}})).inject(a);(new Element("a",{href:"javascript:",text:"\u53d6\u6d88","class":"alert-btn-submit alert-btn-cancel",events:{click:function(){c.close()}}})).inject(a);break;case "tip":0==c.options.delay&&(c.options.delay=5E3),c.dom.alert.inject(document.body)}c.dom.alert.removeClass.delay(100,
c.dom.alert,["bw-tip-hide"]);c.options.mask&&(c.dom.mask=new Element("div",{id:"bw-tip-mask","class":"tip-mask tip-mask-hide"}),c.dom.mask.inject(document.body),c.dom.mask.removeClass.delay(50,c.dom.mask,["tip-mask-hide"]));c.autoclose(c.options.delay)},autoclose:function(a){0!=this.options.delay&&(0>=a?(this.close(),"tip"==this.options.type&&this.options.callback&&this.options.callback.apply(this)):this.autoclose.delay(1E3,this,[a-1E3]))},close:function(){null!=this.dom.alert&&(this.dom.alert.addClass("bw-tip-hide"),
this.dom.alert.dispose.delay(500,this.dom.alert));null!=this.dom.mask&&(this.dom.mask.addClass("tip-mask-hide"),this.dom.mask.dispose.delay(500,this.dom.mask))},dispose:function(){null!=$("bw-tip")&&$("bw-tip").dispose();null!=$("bw-tip-mask")&&$("bw-tip-mask").dispose()}})})(BW);Element.prototype.getBindEvent=function(){return this.retrieve("bind")};
window.addEvent("domready",function(){!function(){var e=$(document.body).get("data-theme-resource");e&&e.split(",").each(function(a){""!=a&&(new Request({url:a,async:!1,onSuccess:function(b,c){b=null;switch(a.substring(a.lastIndexOf(".")+1)){case "css":b=new Element("link",{href:a,rel:"stylesheet"})}b.inject(document.body)}})).get()})}();!function(){var e=[];MooTools.mobile&&e.push("bw-mobile");e.push("bw-platform-"+Browser.platform);e.each(function(a){$(document.body).addClass(a)})}();$$("[data-bind-action]").each(function(e){BW.Bind(e)})});
!function(){MooTools.mobile||window.addEvent("click",function(e){e=$(e.target);if(e.get("data-event-target")){var a=$(e.get("data-event-target"));if(null==a)return;a.fireEvent("click")}if(e.get("data-event-fire")){a=$(e.get("data-event-fire"));if(null==a)return;BW.Bind(a).fire()}if("switch"==e.get("data-type")){a=null;if(e.get("name")){var b=e.get("name");a=e.getNext("input[name="+b+"]");null==a&&(a=new Element("input",{type:"hidden",name:b}),a.inject(e,"after"),e.set({name:null,"data-hidden-name":b}))}null==
a&&(a=e.getNext("input[name="+e.get("data-hidden-name")+"]"));null!=a&&a.set("value",e.get("checked")?1:0)}})}();