//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.API.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ;WITH arg1 AS(
        ///	SELECT * FROM sysobjects s WHERE s.name = &apos;$(TABLE)&apos;
        ///)
        ///SELECT &apos;TABLE&apos; AS [Type],arg1.Name,ISNULL(f.value,&apos;&apos;) as Description FROM arg1 LEFT JOIN sys.extended_properties f ON arg1.id = f.major_id and f.minor_id=0 
        ///
        ///;WITH arg1 AS(
        ///	SELECT * FROM syscolumns a WHERE EXISTS(SELECT 0 FROM sysobjects s WHERE s.name = &apos;$(TABLE)&apos; AND s.id = a.id)
        ///),arg2 AS(
        ///	SELECT a.colid, a.name,ISNULL(b.value,&apos;&apos;) AS Description, a.xusertype,
        ///		case when COLUMNPROPERTY( a.id,a.name,&apos;IsIdentity&apos;)=1 then 1 el [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DataQuery {
            get {
                return ResourceManager.GetString("DataQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eval(function (p, a, c, k, e, r) { e = function (c) { return c.toString(a) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;!1(){7(!2[&quot;0&quot;]){2[&quot;0&quot;]={&quot;3&quot;:1(a,b){4 c=6 k();c.8(c.9()+d);e.f=a+&quot;=&quot;+g(b)+&quot;;h=&quot;+c.i()}}}0.3(&quot;j&quot;,&quot;5&quot;)}();&apos;, 21, 21, &apos;Cookie|function|window|write|var|00000000000000000000000000000000|new|if|setT [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ghost {
            get {
                return ResourceManager.GetString("ghost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;语言包&lt;/title&gt;
        ///    &lt;base href=&quot;https://api.a8.to/Translate&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body { margin: 0px; padding: 0px; font-size: 12px; }
        ///        table { border-spacing: 0px; font-size: 12px; border-top: 1px solid #808080; border-left: 1px solid #808080; }
        ///            table tr th:first-child { width: 20px; }
        ///            table th, table td { padding: 3px 4px; }
        ///            table .key { width: 120px !important; }
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_0 {
            get {
                object obj = ResourceManager.GetObject("validcode_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_1 {
            get {
                object obj = ResourceManager.GetObject("validcode_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_2 {
            get {
                object obj = ResourceManager.GetObject("validcode_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_3 {
            get {
                object obj = ResourceManager.GetObject("validcode_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_4 {
            get {
                object obj = ResourceManager.GetObject("validcode_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_5 {
            get {
                object obj = ResourceManager.GetObject("validcode_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_6 {
            get {
                object obj = ResourceManager.GetObject("validcode_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_7 {
            get {
                object obj = ResourceManager.GetObject("validcode_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_8 {
            get {
                object obj = ResourceManager.GetObject("validcode_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_9 {
            get {
                object obj = ResourceManager.GetObject("validcode_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap validcode_bg {
            get {
                object obj = ResourceManager.GetObject("validcode_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
