window.BW||(window.BW={});
(function(c){c.diagIndex=101;c.diagObj={};c.Diag=new Class({Implements:[Events,Options],options:{name:null,cssname:null,type:null,src:null,close:!0,title:null,drag:!1,width:640,height:480,resize:!1,mask:!1,data:null,store:null,callback:null,closecallback:null},dom:{obj:null,mask:null,element:null},initialize:function(b,d){var a=this;b&&(a.dom.element=b=$(b));a.setOptions(d);null==a.options.name?alert("\u672a\u5b9a\u4e49\u7a97\u53e3\u540d\u5b57"):c.diagObj[a.options.name]?c.diagObj[a.options.name].target.shake():
(c.diagObj[a.options.name]={},c.diagObj[a.options.name].target=a,a.dom.obj=new Element("div",{"class":"diag","data-name":a.options.name,styles:{"margin-top":a.options.height/-2,"margin-left":a.options.width/-2,left:c.diagObj[a.options.name].left,top:c.diagObj[a.options.name].top,width:a.options.width.toInt(),height:a.options.height.toInt(),zIndex:c.diagIndex+2}}),a.dom.obj.inject(document.body),a.options.cssname&&a.dom.obj.addClass(a.options.cssname),a.options.title&&((new Element("div",{"class":"diag-title",
html:"<strong>"+a.options.title+"</strong>"})).inject(a.dom.obj),a.options.drag&&new Drag(a.dom.obj,{handle:a.dom.obj.getElement(".diag-title")})),a.options.close&&(new Element("a",{href:"javascript:","class":"diag-close",events:{click:function(){a.Close()}}})).inject(a.dom.obj,"top"),a.options.resize&&(new Element("a",{href:"javascript:","class":"diag-resize",events:{click:function(){a.Resize(this)}}})).inject(a.dom.obj,"top"),d=0,a.options.title&&(d+=a.dom.obj.getElement(".diag-title").getSize().y),
d=null,a.options.data&&("parent"==a.options.data&&null!=b&&(b=b.getParent("[data-diag-data]"),null!=b&&(a.options.data=b.get("data-diag-data"))),d="string"==typeof a.options.data?a.options.data:Object.toQueryString(a.options.data)),b=new Element("div",{"class":"diag-content","data-bind-post":d}),b.inject(a.dom.obj),a.options.store&&b.store("data",a.options.store),a.options.mask&&(a.dom.mask=new Element("div",{"class":"diag-mask",styles:{zIndex:c.diagIndex+1}}),a.options.cssname&&a.dom.mask.addClass(a.options.cssname),
a.dom.mask.inject(document.body)),a["bind-"+a.options.type]&&a["bind-"+a.options.type].apply(a,[b]),c.diagIndex+=2)},"bind-control":function(b){b.set({"data-bind-action":this.options.src,"data-bind-type":"control","data-bind-callback":this.options.callback,"data-bind-load":this.options.load});new c.BindEvent(b)},"bind-frame":function(b){var c=this.options.height;this.options.title&&(c-=this.dom.obj.getElement(".diag-title").getSize().y);(new Element("iframe",{frameborder:0,width:"100%",height:c,src:this.options.src})).inject(b)},
shake:function(){for(var b=this.dom.obj.getStyle("left").toInt(),c=new Fx.Tween(this.dom.obj,{duration:25,link:"chain"}),a=0;10>a;a++)c.start("left",b+10*(0==a%2?-1:1))},Resize:function(b){b.toggleClass("diag-resize-min");var c=null;"frame"==this.options.type&&(c=this.dom.obj.getElement("iframe"));b.hasClass("diag-resize-min")?(this.dom.obj.setStyles({width:this.options.width/2,height:this.options.height/2}),c&&c.set("height",this.options.height/2-45)):(this.dom.obj.setStyles({width:this.options.width,
height:this.options.height}),c&&c.set("height",this.options.height-45))},Close:function(){var b=this;null!=b.dom.obj&&(c.diagObj[b.options.name].left=b.dom.obj.getStyle("left"),c.diagObj[b.options.name].top=b.dom.obj.getStyle("top"),b.dom.obj.addClass("diag-dispose"),b.dom.close&&b.dom.close.dispose(),b.dom.mask&&b.dom.mask.dispose(),b.options.closecallback&&"function"==typeof b.options.closecallback&&b.options.closecallback.apply(b),function(){b.dom.obj.dispose();b.dom.obj=null;delete c.diagObj[b.options.name];
delete b}.delay(300))}})})(BW);
!function(){window.addEvents({click:function(c){var b=$(c.target);b.get("data-diag-name")&&(c.stop(),new BW.Diag(b,Element.GetAttribute(b,"data-diag-")));if(b.hasClass("diag-user")&&null!=b.get("data-userid")){c.stop();c=Math.min(900,.8*UI.getSize().x).toInt();var d=Math.min(600,.8*UI.getSize().y).toInt();new BW.Diag(b,{name:"UserInfo",cssname:"diag-userinfo",type:"control",src:"/controls/userinfo.html",title:"\u67e5\u770b\u7528\u6237\u8d44\u6599",mask:!0,width:c,height:d,drag:!0,data:{UserID:b.get("data-userid")},
callback:"tip,userinfo-callback"})}}})}();