window.GolbalSetting={Site:null,User:null,Header:null};window.BW||(window.BW={});
!function(d){var b=window.navigator.userAgent;d.platform={x5:/x5/.test(b),ios:/iPhone/i.test(b),android:/Android/i.test(b),windows:/Windows/i.test(b),wechat:/MicroMessenger/i.test(b)};d.run={control:function(){var c=this,a=function(a){c.dom.container.set("html",a);c.callback(a);d.Utils.bindAction.apply(c)},b=null,e="control:"+c.options.action;c.options.cache&&(b=d.Utils.getStore(e));b?a.apply(c,[b]):(new Request.HTML({url:c.options.action,noCache:!c.options.cache,onRequest:function(){d.loading.control&&
d.loading.control.apply(c,[!0])},onComplete:function(){d.loading.control&&d.loading.control.apply(c,[!1])},onSuccess:function(b,g,k,l){c.options.cache&&d.Utils.setStore(e,k);a.apply(c,[k])}})).get()},ajax:function(c){var a=this,b=a.getPostData(),e=function(b){a.callback(b,c)},f="ajax:"+a.options.action+"?"+Object.toQueryString(b),h=null;a.options.cache&&(h=d.Utils.getStore(f));h?e.apply(a,[h]):(new Request.JSON({url:a.options.action,headers:GolbalSetting.Header||{},onRequest:function(){d.loading.ajax&&
d.loading.ajax.apply(a,[!0])},onComplete:function(){d.loading.ajax&&d.loading.ajax.apply(a,[!1])},onFailure:function(a){switch(a.status){case 503:a=null;break;default:a=a.response}a&&(a=a.replace(/<a .+?<\/a>/g,"BetWin 2.0.1"),d.Tip&&new BW.Tip(a))},onSuccess:function(c){e.apply(a,[c]);a.options.cache&&d.Utils.setStore(f,c)}})).post(b)},form:function(){var c=this;"form"==c.dom.element.get("tag")&&c.dom.element.set({events:{submit:function(a){a.stop();var b=this.get("send");Object.forEach(GolbalSetting.Header||
{},function(a,c){b.setHeader(c,a)});b.send({url:c.options.action})}},send:{headers:GolbalSetting.Header||{},onRequest:function(){d.loading.form&&d.loading.form.apply(c,[!0])},onComplete:function(){d.loading.form&&d.loading.form.apply(c,[!1])},onSuccess:function(a){(a=JSON.decode(a))&&a.success&&c.dom.element.reset();c.callback(a)}}})},list:function(){}};d.Utils={getStore:function(c){if(localStorage){var a=localStorage.getItem(c);return a?0==c.indexOf("ajax:")||0==c.indexOf("json:")?JSON.decode(a):
a:null}},setStore:function(c,a){localStorage&&("object"==typeof a&&(a=JSON.encode(a)),localStorage.setItem(c,a))},clearcache:function(c){!function(){if(window.localStorage)for(var a=localStorage.length-1;0<=a;a--){var c=localStorage.key(a);["control","ajax"].each(function(a){0==c.indexOf(a+":")&&localStorage.removeItem(c)})}}();c&&c.apply(this)},bindAction:function(){var c=document.body;this&&this.dom&&this.dom.container&&(c=this.dom.container);c.getElements("[data-bind-action]").each(function(a){new d.Bind(a)})}};
d.Bind=new Class({Implements:[Events,Options],options:{action:null,type:null,event:null,load:null,callback:null,target:null,loading:null,data:null,cache:null,stop:!1,confirm:"\u60a8\u786e\u8ba4\u8981\u8fdb\u884c\u8be5\u64cd\u4f5c\u5417\uff1f"},dom:{element:null,container:null,searchbox:null,pagesplit:null,elements:{}},data:{post:null},loadOptions:function(c){c||(c=this.dom.element);if(c)for(var a=/^data-bind-/,b=0;b<c.attributes.length;b++){var d=c.attributes[b];if(a.test(d.name)){var f=d.name.substr(10);
this.options[f]||(this.options[f]=d.value)}}},setData:function(c){this.data.post=c},getPostData:function(){var c=this,a={};c.options.data&&c.options.data.split(",").each(function(b){switch(b){case "parent":b=c.dom.element.getParent("[data-bind-post]");null!=b&&(a=Object.merge(a,b.get("data-bind-post").parseQueryString()));break;case "url":(b=location.search)&&0==b.indexOf("?")&&(b=b.substr(1),a=Object.merge(a,b.parseQueryString()));break;case "form":var g=c.dom.element.getParent("form,[data-form]");
if(!g)for(b=c.dom.element;null!=b;){g=b.getElement("form,[data-form]");if(!g)break;b=b.getParent()}g&&(a=Object.merge(a,Element.GetData(g)));break;default:b.contains("=")&&(a=Object.merge(a,b.parseQueryString()))}});c.dom.searchbox&&(a=Object.merge(a,Element.GetData(c.dom.searchbox)));c.data.post&&(a=Object.merge(a,c.data.post));return a},initialize:function(c,a){var b=this;b.dom.element=$(c);b.loadOptions();b.setOptions(a);b.dom.container=b.options.target?$(b.options.target):b.dom.element;b.options.load&&
b.options.load.split(",").each(function(a){d.load[a]&&d.load[a].apply(b)});b.options.stop||b.fire();switch(b.options.event){case "click":case "tap":b.dom.element.addEvent(b.options.event,function(){b.fire()});break;case "confirm":b.dom.element.addEvent("click",function(){new BW.Tip(b.options.confirm,{callback:function(a){"confirm"==a.type&&b.fire()}})})}b.dom.element.store("BINDEVENT",b)},fire:function(){d.run[this.options.type]&&d.run[this.options.type].apply(this)},callback:function(c,a){var b=
this;a||(a=b.options.callback);a&&("object"==typeof c&&!c.success&&BW.callback["golbal-error"]&&BW.callback["golbal-error"].apply(b,[c]),a.split(",").each(function(a){d.callback[a]&&d.callback[a].apply(b,[c])}))}});Element.prototype.getBindEvent=function(){return this.retrieve("BINDEVENT")};Element.prototype.fire=function(){var c=this.getBindEvent();c&&c.fire()}}(BW);BW.loading||(BW.loading={});
!function(d){var b=function(c,a){c="loading-"+c;a?this.dom.container.addClass(c):this.dom.container.removeClass(c)};d.ajax=function(c){b.apply(this,["ajax",c])};d.form=function(c){b.apply(this,["form",c])};d.control=function(c){b.apply(this,["control",c])}}(BW.loading);window.addEvent("domready",function(){$$("[data-bind-action]").each(function(d){new BW.Bind(d)});!function(){Object.forEach(BW.platform,function(d,b){d&&document.body.addClass("bw-platform-"+b)})}()});BW.callback||(BW.callback={});
BW.load||(BW.load={});
!function(d){d.dom=function(){var b=this;b.dom.elements||(b.dom.elements={});b.dom.element.getElements("[data-dom]").each(function(c){var a=c.get("data-dom");b.dom.elements[a]?(b.dom.elements[a].length||(b.dom.elements[a]=[b.dom.elements[a]]),b.dom.elements[a].push(c)):b.dom.elements[a]=c})};d.search=function(){for(var b=this,c=null,a=b.dom.element;a;){if("form"==a.get("tag")){c=a;break}var d=a.getElement("form");if(d){c=d;break}a=a.getParent()}c&&(b.dom.searchbox=c,c.addEvent("submit",function(a){b.fire();
a.stop()}))}}(BW.load);!function(d){d["setting-site"]=function(b){b.success&&(GolbalSetting.Site=b.info,console.log(BW.Utils.setStore),BW.Utils.setStore("GolbalSetting.Site",GolbalSetting.Site))}}(BW.callback);
!function(d){d["control-toggle"]=function(){var b={};this.dom.container.getElements("[data-toggle-id]").each(function(c){b[c.get("data-toggle-id")]=c});this.dom.container.getElements("[data-toggle-target]").addEvent("click",function(){var c=this.get("data-toggle-target");Object.forEach(b,function(a,b){b!=c&&(b=a.get("data-toggle-name")||"show",a.hasClass(b)&&a.removeClass(b))});if(b[c]){var a=b[c].get("data-toggle-name")||"show";b[c].toggleClass(a)}})};d["control-select"]=function(b){var c=this;if(b.success)switch(c.dom.element.get("tag")){case "select":switch(typeof b.info){case "object":Object.forEach(b.info,
function(a,b){var d=null;switch(typeof a){case "string":d=new Element("option",{value:a,text:b});break;case "object":d=new Element("optgroup",{label:b}),Object.forEach(a,function(a,b){(new Element("option",{value:b,text:a})).inject(d)})}d&&d.inject(c.dom.element)})}}};d["control-ui"]=function(){this.dom.element.getElements("input[data-type]").each(function(b){switch(b.get("data-type")){case "date":b.set("title","\u65e5\u5386\u63a7\u4ef6")}})};d["control-list-up"]=function(){var b=this.dom.element.getStyle("height").toInt(),
c=this.dom.element.getElement("[data-list-element]");if(c){var a=this.dom.element.getElements("[data-list-element] > *");if(!(1>=a.length)){var d=0,e=!1;c.addEvents({mouseover:function(){e=!0},mouseout:function(){e=!1}});var f=function(){var g=d%a.length*b*-1;0==g?c.addClass("bw-animate-stop"):c.removeClass("bw-animate-stop");(function(){e||(c.setStyle("margin-top",g),d++);f.delay(1E3)}).delay(50)};console.log(c);f.apply()}}}}(BW.callback);
!function(d){d["form-tip"]=function(b){var c=this;new BW.Tip(b.msg,{type:"tip",callback:function(a){(a=c.dom.element.get("data-bind-form-tip"))&&c.callback(b,a)},target:"body"==c.dom.element.get("data-bind-form-tip-target")?null:c.dom.element,closetime:c.dom.element.get("data-bind-form-tip-closetime")})};d["form-alert"]=function(b){var c=this;new BW.Tip(b.msg,{type:"alert",callback:function(a){b.success&&(a=c.dom.element.get("data-bind-form-tip"))&&c.callback(b,a)}})};d["form-fill"]=function(b){if(b.success){var c=
b.info;this.dom.container.getElements("[data-name],[name]").each(function(a){var b=a.get("data-name")||a.get("name"),d=a.get("data-format");if(b=c[b])switch(d&&htmlFunction[d]&&(b=htmlFunction[d](b)),a.get("tag")){case "img":a.set("src",b);break;case "input":case "textarea":a.set("value",b);break;case "section":a.set("html",b);break;default:a.set("text",b)}})}}}(BW.callback);!function(d){d["diag-close"]=function(b){(b=this.dom.element.getParent(".bw-diag"))&&(b=b.retrieve("diag"))&&b.close()}}(BW.callback);
!function(d){d.list=function(b){var c=this.dom.container.getElement("[data-list-element]");if(c){var a=c.retrieve("LIST_TEMPLATE");a||(a=c.get("html"),c.store("LIST_TEMPLATE",a));if(b.success){var d=b.info.list;!d&&b.info.length&&(d=b.info);var e=[];if(0==b.info.RecordCount)switch(c.get("tag")){case "tbody":if(b=c.getPrevious("thead"))b=b.getElements("th").length,e.push('<tr><td colspan="'+b+'"><p class="empty"></p></td></tr>')}else d.each(function(b){b=a.toHtml(b);e.push(b)});c.set("html",e.join(""))}}else new BW.Tip("\u6ca1\u6709\u6307\u5b9adata-list-element\u5143\u7d20")};
d.pagesplit=function(b){var c=this,a=c.dom.container.getNext(".bw-pagesplit");a||(a=new Element("div",{"class":"bw-pagesplit",events:{click:function(a){if(a=$(a.target).get("data-page"))c.setData({PageIndex:a}),c.fire(),c.setData(),a=c.dom.container.getPosition().y,window.scrollTo(0,a)}}}),a.inject(c.dom.container,"after"));a.empty();if(b.info.RecordCount){var d=0==b.info.RecordCount%b.info.PageSize?b.info.RecordCount/b.info.PageSize:Math.floor(b.info.RecordCount/b.info.PageSize)+1;b=b.info.PageIndex;
var e=[];e.push({name:"\u7b2c\u4e00\u9875",page:1});1!=b&&e.push({name:"\u4e0a\u4e00\u9875",page:b-1});for(var f=Math.max(1,b-3);f<=Math.min(d,Math.max(7,b+3));f++)e.push({name:f,page:f,active:f==b});b!=d&&e.push({name:"\u4e0b\u4e00\u9875",page:b+1});e.push({name:"\u6700\u540e\u9875",page:d});e.each(function(b){(new Element("a",{href:"javascript:","class":b.active?"active":"",text:b.name,"data-page":b.page})).inject(a)})}};d.html=function(b){var c=this.dom.container.retrieve("HTML_TEMPLATE",this.dom.container.get("html"));
this.dom.container.store("HTML_TEMPLATE",c);b.info&&(this.dom.container=this.dom.container.set("html",c.toHtml(b.info)))}}(BW.callback);
!function(d){d.Tip=new Class({Implements:[Events,Options],options:{type:"alert",mask:!0,target:$(document.body),callback:function(b){},closetime:null},dom:{mask:null,alert:null},initialize:function(b,c){var a=this;a.setOptions(c);a.options.target||(a.options.target=$(document.body));a.dom.alert=new Element("div",{"class":"bw-tip hide bw-tip-"+a.options.type,html:"<content>"+b+"</content>"});a.dom.alert.inject(a.options.target);a.dom.alert.removeClass.delay(10,a.dom.alert,["hide"]);b=new Element("nav",
{events:{click:function(b){b=$(b.target);"a"==b.get("tag")&&(a.options.callback.delay(100,a,[{type:b.get("class")}]),a.dispose())}}});switch(a.options.type){case "alert":(new Element("a",{"class":"confirm",text:"\u786e\u5b9a"})).inject(b);b.inject(a.dom.alert);break;case "tip":a.options.closetime||(a.options.closetime=3E3);a.dom.alert.addEvent("click",function(){a.options.closetime=0;a.options.callback.apply(a);a.dispose()});break;case "confirm":(new Element("a",{"class":"confirm",text:"\u786e\u5b9a"})).inject(b),
(new Element("a",{"class":"cancel",text:"\u53d6\u6d88"})).inject(b),b.inject(a.dom.alert)}a.options.mask&&(a.dom.mask=new Element("div",{"class":"tip-mask"}),a.dom.mask.inject(a.dom.alert,"after"));a.options.closetime&&function(){a.options.closetime&&(a.options.callback.apply(a),a.dispose.apply(a))}.delay(a.options.closetime)},dispose:function(){this.dom.mask&&(this.dom.mask.addClass("hide"),this.dom.mask.dispose.delay(250,this.dom.mask));this.dom.alert&&(this.dom.alert.addClass("hide"),this.dom.alert.dispose.delay(250,
this.dom.alert))}})}(BW);
!function(d){var b={};d.Diag=new Class({Implements:[Events,Options],options:{name:null,mask:!0,maskclose:!1,width:640,height:480,resize:!1,src:null,type:"control",title:null,data:null,close:!0,cssname:null},initialize:function(c){var a=this;a.setOptions(c);if(a.options.name){b[a.options.name]&&b[a.options.name].close();a.options.mask&&(a.element.mask=new Element("div",{"class":"bw-mask hide "+(a.options.mask?"":"hide"),events:{click:function(){a.options.maskclose&&a.close()}}}),a.element.mask.inject(document.body),
a.element.mask.removeClass.delay(10,a.element.mask,["hide"]));a.element.diag=new Element("div",{"class":"bw-diag "+(a.options.cssname||""),events:{mousewheel:function(a){a.stopPropagation()}},styles:{width:a.options.width,height:a.options.height}});a.element.diag.inject(document.body);a.options.title&&(a.element["diag-title"]=new Element("div",{"class":"bw-diag-title",html:"<h3>"+a.options.title+"</h3>"}),a.element["diag-title"].inject(a.element.diag));a.options.close&&(new Element("a",{href:"javascript:",
"class":"bw-diag-close",events:{click:function(){a.close()}}})).inject(a.element.diag);a.element["diag-content"]=new Element("div",{"class":"bw-diag-content"});a.element["diag-content"].inject(a.element.diag);switch(a.options.type){case "control":if(a.options.data)switch(typeof a.options.data){case "string":a.element["diag-content"].set("data-bind-post",a.options.data);break;case "object":a.element["diag-content"].set("data-bind-post",Object.toQueryString(a.options.data))}new d.Bind(a.element["diag-content"],
{action:a.options.src,type:"control"})}b[a.options.name]=a;a.element.diag.store("diag",a)}},element:{mask:null,diag:null,"diag-title":null,"diag-content":null},open:function(){},close:function(){this.element.diag&&(this.element.diag.addClass("hide"),this.element.diag.dispose.delay(250,this.element.diag));this.element.mask&&(this.element.mask.addClass("hide"),this.element.mask.dispose.delay(250,this.element.mask));b[this.options.name]&&delete b[this.options.name]}});d.DiagOpen=function(b,a){a.name=
b;new BW.Diag(a)}}(BW);window.BW||(window.BW={});
!function(d){d.Frame=new Class({Implements:[Events,Options],options:{container:null,count:0},dom:{container:null,frames:function(){var b="function"==typeof this.dom.container?this.dom.container():this.dom.container,c=b.getElement(".bw-frames");c||(c=new Element("div",{"class":"bw-frames"}),c.inject(b));return c}},data:{frame:[],getFrame:function(b){var c=null;this.data.frame.each(function(a){c||a.name!=b||(c=a.obj)});return c},add:function(b,c){var a=this;1==a.options.count&&0!=a.data.frame.length?
(a.data.frame[0].obj.dispose(),a.data.frame=[{name:b,obj:c}]):(a.data.frame.push({name:b,obj:c}),1==a.data.frame.length?c.addClass("active"):function(){var b=a.data.frame[a.data.frame.length-2].obj;b&&b.hasClass("active")&&b.removeClass("active");c.addClass("active")}.delay(10))},remove:function(b){var c=this,a=b?-1:c.data.frame.length-1;c.data.frame.each(function(c,d){-1==a&&c.name==b&&(a=d+1)});0>a||(c.data.frame.each(function(b,d){if(!(d<a)){var e=b.obj;e.hasClass("active")?(e.removeClass("active"),
function(){e.dispose()}.delay(500)):e.dispose();c.data.frame[d]=null}}),c.data.frame=c.data.frame.clean(),c.data.frame.getLast().obj.addClass("active"))}},initialize:function(b){this.setOptions(b);this.dom.container=this.options.container},open:function(b,c,a,d){b||(b=c);a=a?a.split(","):[];a.push("control-frame");var e=this.data.getFrame.apply(this,[b]);d&&"object"==typeof d&&(d=Object.toQueryString(d));e?this.close(b):(e=new Element("div",{"data-frame-name":b,"class":"frame-item","data-bind-action":c,
"data-bind-type":"control","data-bind-stop":!0,"data-bind-callback":0==a.length?null:a.join(","),"data-bind-post":d||null}),e.store("FRAMES",this),new BW.Bind(e),this.data.add.apply(this,[b,e]),e.inject(this.dom.frames.apply(this)),e.fire())},close:function(b){this.data.remove.apply(this,[b])}});d.callback["control-frame"]=function(){var b=this;b.dom.element.getElements("[data-frame]").addEvent("tap",function(){var c=this.get("data-frame");if(c){var a=b.dom.element.retrieve("FRAMES");switch(c){case "back":a&&
a.close.apply(a);break;case "link":a&&a.open.apply(a,[this.get("data-frame-link-name"),this.get("data-frame-link")])}}});d.OffCanvasObj&&d.OffCanvasObj.close()}}(BW);
!function(d){d.OffCanvasObj=null;d.OffCanvas=new Class({Implements:[Events,Options],options:{mask:null,size:"auto",data:null,cssname:null,action:"bottom",src:null},dom:{mask:null,canvas:null},initialize:function(b){d.OffCanvasObj&&d.OffCanvasObj.close();var c=d.OffCanvasObj=this;c.setOptions(b);c.dom.mask=new Element("div",{"class":"bw-mask "+(c.options.mask||""),events:{click:function(){console.log("\u5173\u95ed");c.close()}}});(b=c.options.data)&&"object"==typeof b&&(b=Object.toQueryString(c.options.data));
c.dom.canvas=new Element("div",{"class":"bw-offcanvas "+c.options.action+" "+(c.options.cssname||""),"data-bind-action":c.options.src,"data-bind-type":"control","data-bind-post":b||null,events:{click:function(a){a.stopPropagation()}}});if(c.options.size)switch(c.options.action){case "top":case "bottom":c.dom.canvas.setStyle("height",c.options.size);break;case "left":case "right":c.dom.canvas.setStyle("width",c.options.size)}c.dom.canvas.inject(c.dom.mask);c.dom.mask.inject(document.body);new BW.Bind(c.dom.canvas);
c.dom.mask.addClass.delay(50,c.dom.mask,["active"])},close:function(){this.dom.mask.removeClass("active");this.dom.mask.dispose.delay(250,this.dom.mask);d.OffCanvasObj=null}})}(BW);
!function(d){d.Tab=new Class({Implements:[Events,Options],options:{nav:[],frame:[],activeName:"active",event:"click",display:0},initialize:function(b){var c=this;c.setOptions(b);var a=null,d=null;c.options.nav.each(function(b,f){b.addEvent(c.options.event,function(){a!=b&&(a&&a.removeClass(c.options.activeName),d&&d.removeClass(c.options.activeName),a=b,d=c.options.frame[f],a.addClass("active"),d.addClass("active"),d.fire.delay(100,d))});f==c.options.display&&b.fireEvent(c.options.event)})}})}(BW);
